version: "3"

services:
  pks-sip:
    container_name: pks-sip
    hostname: sip.pks.local
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      #- ./kamailio.cfg:/etc/kamailio/kamailio.cfg
      - ./tests/db-test:/etc/kamailio/db
    environment:
      #LISTEN_PUBLIC: localhost:5060
      #LISTEN_PRIVATE: localhost:5061
      ENVIRONMENT: dev
      LISTEN_ADVERTISE: 82.122.151.12:5060
      KAMAILIO_LOG_LEVEL: info
      RTPENGINE_URL: rtp.pks.local
      REDIS_URL: redis.pks.local
      ALIAS: sip.pks.local
    depends_on:
      - pks-redis
      - pks-rtp
      - pks-fs-1
    ports:
      - "5060:5060/udp"
      - "5061:5061/udp"
    networks:
      main:
        aliases:
          - pks-sip
  pks-redis:
    container_name: pks-redis
    hostname: redis.pks.local
    image: redis:7-alpine
    networks:
      main:
        aliases:
          - pks-redis
  pks-rtp:
    container_name: pks-rtp
    hostname: rtp.pks.local
    image: registry.gitlab.com/mwolff44/pyfb-rtpproxy:latest
    privileged: true
    environment:
      BIND_NG_PORT: 22222
      PUBLIC_IP: 82.122.151.12
      PORT_MIN: 16384
      PORT_MAX: 16485
    networks:
      main:
        aliases:
          - pks-rtp

  pks-fs-1:
    container_name: pks-fs-1
    hostname: fs1.pks.local
    build:
      context: ./tests/freeswitch
      dockerfile: Dockerfile
    logging:
       options:
         max-size: 50m
    volumes:
      - ./tests/freeswitch/conf:/usr/local/freeswitch/conf
    networks:
      main:
        aliases:
          - pks-fs-1

networks:
  main: