basePath: /api/v1
definitions:
  api_errors.ApiError:
    properties:
      error:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
  models.Gateway:
    properties:
      created_at:
        description: Creation time
        type: string
      id:
        description: Gateway ID
        type: integer
      ipaddress:
        description: IP Address of the gateway
        type: string
      name:
        description: Name of the gateway
        type: string
      port:
        description: SIP Port of the gateway
        type: string
      updated_at:
        description: Updated time
        type: string
    required:
    - ipaddress
    - name
    - port
    type: object
host: localhost:8080
info:
  contact:
    name: Mathias WOLFF
    url: https://www.pyfreebilling.com
  description: This is the documentation API for P-KISS-SBC.
  license:
    name: AGPL 3.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: P-KISS-SBC API
  version: 1.0.0
paths:
  /gateways:
    get:
      description: Responds with the list of gateways as JSON.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Gateway'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api_errors.ApiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api_errors.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api_errors.ApiError'
      summary: Get a paginated list of gateways
      tags:
      - gateways
  /gateways/:
    post:
      description: Takes a gateway JSON and stores in DB. Return saved JSON.
      parameters:
      - description: gateway object
        in: body
        name: gateway
        required: true
        schema:
          $ref: '#/definitions/models.Gateway'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Gateway'
      summary: Creates a new gateway object
      tags:
      - gateways
  /gateways/{id}:
    get:
      description: Get gateway by ID
      parameters:
      - description: Gateway ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Gateway'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api_errors.ApiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api_errors.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api_errors.ApiError'
      summary: Show a gateway
      tags:
      - gateways
    put:
      description: update gateway.
      parameters:
      - description: id of the gateway
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Gateway'
      summary: Update a gateway
      tags:
      - gateways
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
