basePath: /api/v1
definitions:
  models.Gateway:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      ipaddress:
        type: string
      name:
        type: string
      port:
        type: string
      updatedAt:
        type: string
    required:
    - ipaddress
    - name
    - port
    type: object
host: localhost:8080
info:
  contact:
    name: Mathias WOLFF
    url: https://www.pyfreebilling.com
  description: This is the documentation API for P-KISS-SBC.
  license:
    name: AGPL 3.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: P-KISS-SBC API
  version: "1.0"
paths:
  /gateways:
    get:
      description: Responds with the list of gateways as JSON.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Gateway'
            type: array
      summary: Get a paginated list of gateways
      tags:
      - gateways
  /gateways/:
    post:
      description: Takes a gateway JSON and stores in DB. Return saved JSON.
      parameters:
      - description: gateway object
        in: body
        name: gateway
        required: true
        schema:
          $ref: '#/definitions/models.Gateway'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Gateway'
      summary: Creates a new gateway object
      tags:
      - gateways
  /gateways/{id}:
    get:
      description: Returns the gateway whose id matches the id.
      parameters:
      - description: search gateway by id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Gateway'
      summary: Gets a gateway by ID
      tags:
      - gateways
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
